"""
[F02_File.py]
Purpose: Functions for file and folder management, 
    including filtering, relocating, and organizing files. 
    Includes tools for handling file extensions, keywords, and directory structures. 
    Also offers functions for previewing, consolidating, and managing files using Tkinter dialogs.
    
Author: Meng-Chi Ed Chen
Date: 2023-06-06
Reference:
    1.
    2.
Status: Complete.
"""
import sys, os, openpyxl, tkinter, shutil, subprocess
import pandas as pd
from datetime import datetime
from tabulate import tabulate

import tkinter as tk
from tkinter import filedialog


#[1] Directory and path management - Start






def get_working_dir_from_sysargv():
    dir_working, dir_bsn = None, None
    #[1] Retrieve the working directory from command-line arguments
    #print(f'sys.argv = {sys.argv}')
    
    if len(sys.argv) < 2:
        raise ValueError(f'\n-- No working directory provided from sys.argv:\n{sys.argv}\n-- Use the existing dir_img_folder in code.')
    elif 'ipykernel_launcher.py' in sys.argv[0]:
        raise ValueError('\n-- Detected ipynb environment. Please provide dir_working manually in the code.')
    else:
        raw = sys.argv[1]
        #[3] sanitize: trim whitespace and remove surrounding quotes (handles cases like ...SARD-03_launchers")
        if isinstance(raw, str):
            raw = raw.strip()
            if raw[0] in ['"', "'"]:
                raw = raw[1:]
            if raw[-1] in ['"', "'"]:
                raw = raw[:-1]
        dir_working = os.path.normpath(raw)
        timestamp = datetime.now().strftime("%Y-%m%d-%H%M%S")
        print(f'-- [{timestamp}] Working directory received: \n{dir_working}')
        dir_bsn = os.path.basename(dir_working)
        
    return dir_working, dir_bsn





def fully_remove_previous_test_files(dir_img_folder, prep_for_stage = 'coarse_matching'):
    """
    list_keywords_to_keep will override list_keywords_to_dump.
    """
    
    #[1] Remove files that will be generated by coarse_matching stage and fine_matching stage. Must keep the original images.
    if prep_for_stage == 'coarse_matching':
        # Full reset before Stage I: dump every artifact from BOTH stages. Stage I tags:
        # 00-kernel, 01-mark, 02-ovlp, 03-refine (+ legacy blur/sharpen/.xlsx/filter stats);
        # Stage II tags: 10-init, 11-best, 12-learning, 13-2D, 14-3D, 15-anime.
        # Keep only the original images, .bat, and notes.
        list_keywords_to_dump = ['blurred', 'blur', 'blr', 'sharpen', 'shp',
                                        'enh', 'marked', 'mark', 'mk', 'crop', 'overlap', 'ovlp',
                                        'arrow', '.xlsx', 'learning', 'optimiz', 'map',
                                        'log', 'kernel', 'filter', 'opt', 'keep', 'refine',
                                        'initial', 'init', 'final', 'best', '2D', '3D', 'process', 'anime', '.gif']
        list_keywords_to_keep = ['.bat', 'note']

    #[2] Remove files that will be generated by fine_matching stage. Must keep the original images and the Stage I result <trial>.xlsx (needed for initialization).
    elif prep_for_stage == 'fine_matching':
        # Remove ONLY the fine-stage (Stage II) outputs: 10-init, 11-best, 12-learning, 13-2D,
        # 14-3D, 15-anime. Keep the original images and ALL Stage I products (00-kernel, 01-mark,
        # 02-ovlp, 03-refine), especially the Stage I result <trial>.xlsx that initializes Stage II.
        # ('init' also catches the legacy 'initial' name.)
        list_keywords_to_dump = ['init', 'best', 'learning', '2D', '3D', 'anime', '.gif']
        list_keywords_to_keep = ['.bat', 'note', '.xlsx']
    
    else:
        raise ValueError(f'\n⚠️[Error] Invalid prep_for_stage: {prep_for_stage}. Please check the code and provide a valid stage name.')
    
    
    
    #[4] Filter files.    
    list_paths_to_remove, list_bsn_to_remove \
        = filter_file_in_dir_with_keywords(dir_img_folder, list_keywords_to_dump, list_keywords_to_keep, print_bsn=False)

    #[5] If no files neede to be removed.
    if len(list_paths_to_remove) == 0:
        #print('\n(Nothing need to be removed.)')
        return None

    #[8] Create dir_dump and move files.
    dir_dump = os.path.join(dir_img_folder, '00_dump')
    os.makedirs(dir_dump, exist_ok=True)
    list_path_files_relocate(list_paths_to_remove, dir_dump)
    
    return list_paths_to_remove
    



#[1] Directory and path management - End










#[3] General file and folder - Start

def find_certain_ext_in_dir(dir_folder, ext):
    list_paths = [os.path.join(dir_folder, file) for file in os.listdir(dir_folder) if file.endswith(ext)]
    list_bsns = [file for file in os.listdir(dir_folder) if file.endswith(ext)]
    return list_paths, list_bsns


def find_list_exts_in_dir(  dir_folder, 
                            list_exts, 
                            list_kwd_exclude = ['processed', 'bat', 'exclude']):
    """
    Fing files with certain extensions in a directory, 
    excluding those with specified keywords.
    """
    #[1] Normalize extensions
    if list_exts is None:
        exts = None
    else:
        if isinstance(list_exts, str):
            list_exts = [list_exts]
        exts = [('.' + s.lstrip('.')).lower() for s in (x.strip() for x in list_exts) if s and s.strip()]
        if not exts:
            exts = None
    
    #[3] Filter files
    list_paths  = [f for f in os.listdir(dir_folder) if os.path.isfile(os.path.join(dir_folder, f))]
    list_bsns   = [f for f in list_paths
                    if not any(kwd in f.lower() for kwd in list_kwd_exclude)
                    and (exts is None or any(f.lower().endswith(ext) for ext in exts))]
    list_paths = [os.path.join(dir_folder, f) for f in list_bsns]
    cnt_files = len(list_paths)
    return list_paths, list_bsns, cnt_files




def filter_files_by_extension(  dir_folder, 
                                list_exts            = [], 
                                include_or_exclude  = 'include', 
                                remove_file         = False):
    print(f'\n[filter_files_by_extension]')
    
    #[1] Check if directory exists
    if not os.path.isdir(dir_folder):
        raise FileNotFoundError(f'The directory {dir_folder} was not found.')
    
    #[2] Get list of files in the directory, no folders.
    if include_or_exclude == 'include':
        list_path_match = [ os.path.join(dir_folder, file)
                                for file in os.listdir(dir_folder)
                                if any(file.lower().endswith(ext) for ext in list_exts) ]
        
    elif include_or_exclude == 'exclude':
        list_path_match = [ os.path.join(dir_folder, file)
                                for file in os.listdir(dir_folder)
                                if not any(file.lower().endswith(ext) for ext in list_exts) ]
    else:
        raise ValueError(f'Invalid value for include_or_exclude: {include_or_exclude}. Use "include" or "exclude".')
    cnt_match = len(list_path_match)
    
    #[3] Optionally remove files
    if remove_file:
        for i, path_original in enumerate(list_path_match):
            os.remove(path_original)
            print(f'[{i+1:03d}/{cnt_match}] \tRemoved: {os.path.basename(path_original)}')
    return list_path_match, cnt_match



"""
sys.path.append(r'D:\01_Floor\a_Ed\09_EECS\10_Python\00_Classes and Functions')
import F02_File as F02_File #type: ignore
list_kwd_yes_or_1=[]
list_kwd_no_or_2=[]
list_paths, list_bsns = F02_File.filter_file_in_dir_with_keywords(dir_sort, list_kwd_yes_or_1, list_kwd_no_or_2, False)
"""



def filter_file_in_dir_with_keywords(dir_folder, list_kwd_yes_or_1=[], list_kwd_no_or_2=[], print_bsn = False):
    print(f'\n[filter_file_in_dir_with_keywords] dir_folder = {dir_folder}') if print_bsn else None
    #[1] Check if directory exists
    if not os.path.isdir(dir_folder):
        raise FileNotFoundError(f'The directory {dir_folder} was not found.')
    
    #[2] Get list of files in the directory, no folders.
    list_bsns = [file for file in os.listdir(dir_folder) if os.path.isfile(os.path.join(dir_folder, file))]
    cnt_before = len(list_bsns)
    
    #[3] Filter names by keywords to select (if list_kwd_yes_or_1 is not empty list).
    if list_kwd_yes_or_1 != []:
        list_bsns = [file for file in list_bsns if any(keyword in file for keyword in list_kwd_yes_or_1)]
    
    #[4] Filter names by keywords to discard (if list_kwd_no_or_2 is not empty list).
    if list_kwd_no_or_2 != []:
        list_bsns = [file for file in list_bsns if not any(keyword in file for keyword in list_kwd_no_or_2)]
        
    #[5] Generate file paths and orint
    list_paths = [os.path.join(dir_folder, file) for file in list_bsns]
    cnt_after = len(list_bsns)
    if print_bsn:
        print(f'\n--  Count (before, after) = {cnt_before}, {cnt_after}. list_bsns: \n{list_bsns}', end='\n\n')
    return list_paths, list_bsns


def filter_folders_in_dir_with_keywords(dir_folder, list_kwd_yes_or_1=[], list_kwd_no_or_2=[], print_bsn=False):
    print(f'\n[filter_folders_in_dir_with_keywords] dir_folder = {dir_folder}')
    
    #[1] Check if directory exists
    if not os.path.isdir(dir_folder):
        raise FileNotFoundError(f'The directory {dir_folder} was not found.')
    
    #[2] Get list of folders in the directory, no files.
    list_bsns = [folder for folder in os.listdir(dir_folder) if os.path.isdir(os.path.join(dir_folder, folder))]
    cnt_before = len(list_bsns)
    
    #[3] Filter folder names by keywords to select (if list_kwd_yes_or_1 is not empty list).
    if list_kwd_yes_or_1 != []:
        list_bsns = [folder for folder in list_bsns if any(keyword in folder for keyword in list_kwd_yes_or_1)]
    
    #[4] Filter folder names by keywords to discard (if list_kwd_no_or_2 is not empty list).
    if list_kwd_no_or_2 != []:
        list_bsns = [folder for folder in list_bsns if not any(keyword in folder for keyword in list_kwd_no_or_2)]
    
    #[5] Generate folder paths and print
    list_dirs = [os.path.join(dir_folder, folder) for folder in list_bsns]
    cnt_after = len(list_bsns)
    if print_bsn:
        print(f'\n--  Count (before, after) = {cnt_before}, {cnt_after}. list_bsns: \n{list_bsns}', end='\n\n')
    return list_dirs, list_bsns



def check_if_dir_or_file_exists(path):
    if os.path.isdir(path):
        return 'dir'
    elif os.path.isfile(path):
        return 'file'
    else:
        return 'none'




def open_a_folder_on_windows(dir_folder):
    """
    Opens the specified folder on Windows using File Explorer.
    
    Parameters:
    dir_folder (str): The path to the folder to open.
    """
    try:
        # Ensure the directory exists
        if os.path.exists(dir_folder):
            # Use subprocess to open the folder in File Explorer
            subprocess.run(['explorer', dir_folder], check=True)
            print(f"Folder '{dir_folder}' opened successfully.")
        else:
            print(f"The directory '{dir_folder}' does not exist.")
    except Exception as e:
        print(f"Error opening folder '{dir_folder}': {e}")



#[3] General file and folder - End







#[4] Moving or Dumping Files - Start
"""
Try to avoid using program to delete files because it's irreversible. 
Just name the dump_folder_name='01_delete' and then delete it mannually later.
Don't add a variable of delete=False.
"""


def make_dir_if_not_exist(dir_to_make=None):
    #[1] If dir_to_make is not provided, make a dir at current directory with timestamp as folder name.
    if dir_to_make is None:
        dir_current = os.path.dirname(os.path.abspath(__file__))
        timestamp = datetime.now().strftime("%Y-%m%d-%H%M%S")
        dir_to_make = os.path.join(dir_current, f'{timestamp}_dir_name')
        
    #[2] Make dir.
    try:
        os.mkdir(dir_to_make)
        print(f'\n[make_dir_if_not_exist] ☑️ Directory was not exists. Just made one: {dir_to_make}')
    except FileExistsError:
        print(f'\n[make_dir_if_not_exist] ✅ Directory already exists.')


def relocate_single_file(i_old_path, dir_new):
    file_name = os.path.basename(i_old_path)
    destination_path = os.path.join(dir_new, file_name)

    #[2] Move the file and handle potential naming conflicts
    try: 
        shutil.move(i_old_path, destination_path)
        
    #[3] Handle the cases if file already exists.
    except shutil.Error:
        bsn_ext = os.path.splitext(file_name)
        suffix = 1
        new_file_name = f'{bsn_ext[0]}_dup{suffix}{bsn_ext[1]}'
        new_destination_path = os.path.join(dir_new, new_file_name)

        while os.path.exists(new_destination_path):
            suffix += 1
            new_file_name = f'{bsn_ext[0]}_dup{suffix}{bsn_ext[1]}'
            new_destination_path = os.path.join(dir_new, new_file_name)

        shutil.move(i_old_path, new_destination_path)

def list_path_files_relocate(list_path, dir_dest):
    #[1] Make directory
    make_dir_if_not_exist(dir_dest)
    #[2] Iterate through the file list to move files
    for i_path in list_path:
        relocate_single_file(i_path, dir_dest)





def batch_file_relocate(dir_folder, list_kwd_yes_or_1=[], list_kwd_no_or_2=[], dump_folder_name='01_dump', print_bsn=False):
    print('\n[batch_file_relocate]')
    
    #[1] Filter files
    list_paths, list_bsns = filter_file_in_dir_with_keywords(dir_folder, list_kwd_yes_or_1, list_kwd_no_or_2, print_bsn)
    cnt = len(list_paths)
    if cnt == 0:
        print(f'-- There is nothing we need to move. File count = {cnt}.')
        return [], []
    
    #[2] Relocate files using the helper function
    dir_dump = os.path.join(dir_folder, dump_folder_name)
    list_path_files_relocate(list_paths, dir_dump)
    
    #[3] Final report
    if print_bsn:
        print(f'--  Finish moving {cnt} files. list_bsns: \n{list_bsns}\n\n')
    
    return list_paths, list_bsns




def relocate_single_folder(dir_original, dir_destination_parent, delete_original=True):
    """
    Relocate all files from a folder to a new directory. 
    If the destination directory does not exist, it will be created.
    """
    print(f'\n[relocate_single_folder] dir_original = {dir_original}')
    
    #[1] Check if the directory exists
    if not os.path.isdir(dir_original):
        raise FileNotFoundError(f'The directory {dir_original} was not found.')
    
    #[2] Get the list of files in the directory
    list_files = [os.path.join(dir_original, file) for file in os.listdir(dir_original) if os.path.isfile(os.path.join(dir_to_move, file))]
    
    #[3] Create a new directory to move the files
    dir_new = os.path.join(dir_destination_parent, os.path.basename(dir_original))
    make_dir_if_not_exist(dir_new)
    
    #[4] Relocate files to the new directory
    list_path_files_relocate(list_files, dir_new)
    
    #[5] Optionally delete the original folder if specified
    if delete_original:
        try:
            os.rmdir(dir_original)
            print(f'-- Original folder {dir_original} deleted.')
        except OSError:
            print(f'-- Could not delete {dir_original}. Ensure it is empty or not in use.')
    
    #[6] Final report
    print(f'-- Finished relocating {len(list_files)} files from {dir_original} to {dir_new}.')
    return dir_new



#[4] Moving or Dumping Files - End






#[5] Other less used file related functions - End


def collect_files_in_dir_and_subdir_with_keywords_in_bsn(dir, list_kwd_no_or_1 = [], list_kwd_yes_or_2 = [], list_kwd_yes_or_3 = []):
      print('\n[collect_files_in_dir_and_subdir_with_keywords_in_bsn]')
      #[1] Check if directory exists
      if not os.path.isdir(dir):
            raise FileNotFoundError(f"The directory '{dir}' was not found.")
      #[2] Initialize a list to hold the full paths of the files that match the keywords
      list_path = []
      #[3] Walk through the directory and its subdirectories to get a list of files
      for dirpath, _dirnames, basenames in os.walk(dir):
            for iter_bsn in basenames:
                  # Apply the filters progressively, skipping the file as soon as one condition fails
                  if list_kwd_no_or_1 and any(keyword in iter_bsn for keyword in list_kwd_no_or_1):
                        continue  # Skip this file as it contains a keyword from list_kwd_no_or_1
                  if list_kwd_yes_or_2 and not any(keyword in iter_bsn for keyword in list_kwd_yes_or_2):
                        continue  # Skip this file as it doesn't contain any keyword from list_kwd_yes_or_2
                  if list_kwd_yes_or_3 and not any(keyword in iter_bsn for keyword in list_kwd_yes_or_3):
                        continue  # Skip this file as it doesn't contain any keyword from list_kwd_yes_or_3
                  # If the function reaches this point, the file matches all criteria
                  list_path.append(os.path.join(dirpath, iter_bsn))
      return list_path


def count_files_in_dir_and_subdir_with_keywords_in_bsn(dir, list_kwd_yes_or_1):
      print('\n[collect_files_in_dir_and_subdir_with_keywords_in_bsn]')
      print('\n--(Index from 0 to len(list_kwd_yes_or_1)-1 are the numbers that falls into these catagories.)')
      #[1] Check if directory exists
      if not os.path.isdir(dir):
            raise FileNotFoundError(f"The directory '{dir}' was not found.")
      #[2] Initialize a list to hold the full paths of the files that match the keywords
      int_total_kwd = len(list_kwd_yes_or_1)
      list_kwd_count = [0] * (int_total_kwd + 2)
      #[3] Walk through the directory and its subdirectories to get a list of files
      for cnt, output  in enumerate(os.walk(dir)):
            dirpath, _dirnames, basenames = output
            #[4] Iterate through basenames in dir and subdir.
            for iter_bsn in basenames:
                  no_match = 0
                  #[5] Iterate through kwywords. 
                  for cnt_kwd, iter_kwd in enumerate(list_kwd_yes_or_1):
                        #print(f'[{cnt}] {iter_bsn}, {iter_kwd}')
                        if iter_kwd in iter_bsn:
                              list_kwd_count[cnt_kwd] += 1
                              #print(f'--list_kwd_count[{cnt_kwd}] += 1')
                        else:
                              no_match += 1
                  if no_match == int_total_kwd:
                        list_kwd_count[int_total_kwd] += 1
                  list_kwd_count[int_total_kwd + 1] += 1
      return list_kwd_count




def check_if_two_folders(dir_master, dir_slave, slave_replace_with, list_kwd_yes_or_1, list_kwd_no_or_2):
    # [1] List of files in two folders.
    list_paths_m, list_bsn_m = filter_file_in_dir_with_keywords(dir_master, list_kwd_yes_or_1, list_kwd_no_or_2, False)
    list_paths_s, list_bsn_s = filter_file_in_dir_with_keywords(dir_slave, list_kwd_yes_or_1, list_kwd_no_or_2, False)

    # [6] Split element with "_reduced".
    if slave_replace_with:
        str_replace, str_with = slave_replace_with
        list_bsn_s = [filename.replace(str_replace, str_with) for filename in list_bsn_s]

    # [8] Check if similar.
    if sorted(list_bsn_m) == sorted(list_bsn_s):
        print('All background sample images have a reduced version.')
    else:
        print('Does not match. Clear the reduced folder and process again.')

    # [9] Remove all the files (no folders) in the dir_slave.
    for iter_r in os.listdir(dir_slave):
        path_iter_r = os.path.join(dir_slave, iter_r)
        if os.path.isfile(path_iter_r):
            os.remove(path_iter_r)

    # [12] Copy every file from dir_master to dir_slave.
    for file_path in list_paths_m:
        shutil.copy(file_path, dir_slave)


#2024-07-06_This function is not working as expected. Still improving.
def consolidate_folders(new_folder_name=None):
    """
    1. Ask user to select one or more source folders (list_path_scf).
    2. Count the files in these folders (list_file_cnt_scf).
    3. Create destination folder (dir_dest).
    4. Copy everything in list_path_scf into dir_dest.
    5. Check if the sum of list_file_cnt_scf is the number of files in dir_dest, and print result.
    """
    #[1] Tkinter to select folders.
    root = tk.Tk()
    root.withdraw()  # Hide the root window
    file_paths = filedialog.askopenfilenames(title="Select folders")
    
    # Get unique folder paths
    list_path_scf = list(set(os.path.dirname(path) for path in file_paths))
    
    #[2] Count files in the selected folders.
    list_bsn_scf = [os.path.basename(folder) for folder in list_path_scf]
    list_file_cnt_scf = [len(os.listdir(folder)) for folder in list_path_scf]
    
    #[3] If new_folder_name not provided, name it with the first folder.
    path_1st_scf = list_path_scf[0]
    dir_1st_scf = os.path.dirname(path_1st_scf)
    if not new_folder_name:
        bsn_1st_folder = os.path.basename(path_1st_scf)
        new_folder_name = f'{bsn_1st_folder} (et al)'
    dir_dest = os.path.join(dir_1st_scf, new_folder_name)
    
    #[4] Make dir.
    try:
        os.mkdir(dir_dest)
        print("--Directory didn't exist. Just made one.")
    except FileExistsError:
        print("--Directory already exists. Skipping directory creation.")
    
    #[5] Copy files from source folders to destination folder.
    total_files_copied = 0
    for folder in list_path_scf:
        for item in os.listdir(folder):
            s = os.path.join(folder, item)
            d = os.path.join(dir_dest, item)
            if os.path.isdir(s):
                shutil.copytree(s, d, dirs_exist_ok=True)
            else:
                shutil.copy2(s, d)
            total_files_copied += 1
    
    #[6] Verify if the sum of list_file_cnt_scf is the number of files in dir_dest.
    total_files_in_scf = sum(list_file_cnt_scf)
    total_files_in_dest = len(os.listdir(dir_dest))
    if total_files_copied == total_files_in_dest == total_files_in_scf:
        print(f"Consolidation successful: {total_files_copied} files copied.")
    else:
        print(f"Consolidation mismatch: {total_files_in_scf} files expected, "
              f"{total_files_copied} files copied, {total_files_in_dest} files in destination.")

    return dir_dest


def list_all_file_and_folders_in_dir(dir_folder, first_cnt_files=20):
    print(f'\n[list_all_file_and_folders_in_dir] {dir_folder}\n (Listing first {first_cnt_files} items.)')
    try:
        #[1] Check if the directory exists
        if not os.path.isdir(dir_folder):
            raise FileNotFoundError(f"The directory '{dir_folder}' does not exist.")
        
        #[2] List all files and folders in the directory
        list_folder_and_files = os.listdir(dir_folder)
        
        #[3] Limit the number of entries to the first `first_cnt_files`
        limited_list = list_folder_and_files[:first_cnt_files]
        
        #[4] Print each entry on a new line
        cnt = len(limited_list)
        for i, entry in enumerate(limited_list):
            print(f'[{i+1:03d}/{cnt:03d}] \t{entry}')
        
        return limited_list
    
    except Exception as e:
        print(f"Error: {e}")


def move_all_files_to_the_surface(dir_main, print_status=False):
    """
    Moves all files in the subdirectories into the main directory and removes empty folders.

    Parameters:
    dir_main (str): The main directory path.
    print_status (bool): Whether to print status messages. Default is False.
    """
    print('\n[move_all_files_to_the_surface]')
    
    #[1] Ensure the main directory exists
    if not os.path.isdir(dir_main):
        print(f'Provided path is not a directory: {dir_main}')
        return
    
    #[2] Traverse through all subdirectories
    for root, dirs, files in os.walk(dir_main, topdown=False):
        if root == dir_main:
            continue  # Skip the main directory itself

        #[3] Move files to the main directory
        for sub_item in files:
            sub_item_full_path = os.path.join(root, sub_item)
            new_item_path = os.path.join(dir_main, sub_item)

            try:
                os.rename(sub_item_full_path, new_item_path)
                if print_status:
                    print(f'-- Moved: {sub_item} to {os.path.basename(dir_main)}')
            except FileExistsError:
                if print_status:
                    print(f'-- File already exists: {new_item_path}. Skipping.')
            except FileNotFoundError:
                if print_status:
                    print(f'-- File not found: {sub_item_full_path}. Skipping.')
            except Exception as e:
                if print_status:
                    print(f'-- Error moving file {sub_item_full_path}: {e}')

        #[4] Remove empty directories
        remove_folder_if_empty(root)


def remove_folder_if_empty(dir_folder):    
    #[1] Check if the directory exists
    if not os.path.isdir(dir_folder):
        print(f'-- The directory {dir_folder} does not exist. Skipping removal.')
        return
    
    #[2] Check if the directory is empty
    if not os.listdir(dir_folder):
        try:
            os.rmdir(dir_folder)
            print(f'-- Removed empty folder: {dir_folder}')
        except OSError as e:
            print(f'-- Error removing folder {dir_folder}: {e}')
    else:
        print(f'-- The directory {dir_folder} is not empty. Skipping removal.')



def replace_bsnext_with_complete_string(list_file_paths, str_old, str_new):
    print(f'\n[replace_with_complete_string] replacing "{str_old}" with "{str_new}".')
    
    #[1] Check if the given directory exists
    for i, iter_path_file in enumerate(list_file_paths):
        dir_path, bsn_ext = os.path.split(iter_path_file)
        new_bsn_ext = bsn_ext.replace(str_old, str_new)
        new_iter_path_file = os.path.join(dir_path, new_bsn_ext)
        
        #[2] Check if the file names are different and if the original file exists
        if bsn_ext != new_bsn_ext and os.path.exists(iter_path_file):
            os.rename(iter_path_file, new_iter_path_file)
            print(f'[{i:03d}] Renamed as: {new_bsn_ext}')


def preview_files_and_folders_in_dir(dir_folder, preview_cnt=20):
    """
    Keep this preview function simple. Do not add other function like file_only or list_bsn.
    """
    print(f'\n[preview_files_and_folders_in_dir] {dir_folder}')
    try:
        #[1] Check if the directory exists
        if not os.path.isdir(dir_folder):
            raise FileNotFoundError(f"The directory '{dir_folder}' does not exist.")
        
        #[2] List all files and folders in the directory
        list_folder_and_files = os.listdir(dir_folder)
        
        #[3] Limit the number of entries to the first `first_cnt_files`
        limited_list = list_folder_and_files[:preview_cnt]
        
        #[4] Print each entry on a new line
        cnt = len(limited_list)
        for i, entry in enumerate(limited_list):
            print(f'-- [{i+1:03d}/{cnt:03d}] \t{entry}')
        
        return limited_list
    
    except Exception as e:
        print(f"Error: {e}")

#[5] Other less used file related functions - End






#[6] Warning - Start

def only_allow_certain_files(dir_check, file_only=True, list_ext_no_dot=['png', 'jpg', 'jpeg', 'gif'], list_kwd_exclude=[]):
    #[1] List all files and folders in the directory
    list_folder_and_files = os.listdir(dir_check)
    
    #[2] Count folders and optionally raise a warning if file_only is True
    cnt_folder = sum(1 for item in list_folder_and_files if os.path.isdir(os.path.join(dir_check, item)))
    if file_only and cnt_folder > 0:
        print(f'\t-- File only. Please remove {cnt_folder} folders in the directory. (Ignoring folders and keep going.)')
        
        #[3] Filter out only files if file_only is set to True
        list_folder_and_files = [f for f in list_folder_and_files if os.path.isfile(os.path.join(dir_check, f))]
    
    #[4] Create empty lists to store filtered paths and basenames with extensions
    list_path_filtered = []
    list_bsnext_filtered = []
    
    #[5] Loop through each file and filter by extension
    for iter_path in list_folder_and_files:
        bsn_ext = os.path.basename(iter_path)
        bsn, ext = os.path.splitext(bsn_ext)
        ext = ext.lower().strip('.')  # Convert to lowercase and remove the dot for comparison
        
        #[6] Append to filtered lists if the extension matches
        if ext in list_ext_no_dot:
            list_path_filtered.append(os.path.join(dir_check, iter_path))
            list_bsnext_filtered.append(bsn_ext)
    
    #[7] Filter names by keywords to discard (if list_kwd_exclude is not empty).
    if list_kwd_exclude:
        # Apply keyword filtering
        filtered_indices = [
            i for i, file in enumerate(list_bsnext_filtered)
            if not any(keyword in file for keyword in list_kwd_exclude)
        ]
        list_path_filtered = [list_path_filtered[i] for i in filtered_indices]
        list_bsnext_filtered = [list_bsnext_filtered[i] for i in filtered_indices]
    
    #[8] Return the filtered lists
    return list_path_filtered, list_bsnext_filtered






def tkinter_select_multiple_files(dialog_title='Select files', allow_close=False):
    """
    Necessary import statement:
    import os, sys, tkinter
    from tkinter import filedialog
    """
    #[1] Create a window (or container) for the Tkinter GUI (Graphical User Interface) toolkit.
    root = tkinter.Tk()
    root.withdraw()  # Hide the main window since we don't need to see it.
    
    try:
        # [2] Open a file dialog to select multiple files
        list_path_file = tkinter.filedialog.askopenfilenames(title=dialog_title)
        if list_path_file:
            # [3] Extract the base names of the selected files
            list_bsn_file = [os.path.basename(path_file) for path_file in list_path_file]
            # [4] Clean the paths
            list_path_file = [os.path.normpath(path_file) for path_file in list_path_file]
            print('--Selected files:', list_path_file)
            return list_path_file, list_bsn_file
        else:
            # [5] Allow no file selected
            if allow_close:
                return None, None
            # [6] Exit the program if no files are selected
            else:
                print('--No files selected. Exiting.')
                sys.exit()
    except Exception as e:
        print(f'--An error occurred: {e}')
        return None, None
    finally:
        # [7] Release resources
        root.destroy()





#[6] Warning - End




#[7] tkinter select file or folder - Start


def tkinter_select_file(dialog_title='Select a file', allow_close=False):
    """
    Necessary import statement:
    import os, sys, tkinter
    from tkinter import filedialog
    """
    #[1] Create a window (or container) for the Tkinter GUI (Graphical User Interface) toolkit.
    root = tkinter.Tk()
    root.withdraw()  # Hide the main window since we don't need to see it.
    
    try:
        path_file = tkinter.filedialog.askopenfilename(title=dialog_title)
        if path_file:
            #[2] Extract the base name of the selected file.
            bsn_file = os.path.basename(path_file)
            #[3] Clean the path.
            path_file = os.path.normpath(path_file)
            print('--path_file:', path_file)
            return path_file, bsn_file
        else:
            #[4] Allow no file selecte.
            if allow_close:
                return None, None
            #[5] Exit the program if no file is selected.
            else:
                print('--No file selected. Exiting.')
                sys.exit()
    except Exception as e:
        print(f'--An error occurred: {e}')
        return None, None
    finally:
        #[6] Release resources.
        root.destroy()


def tkinter_select_directory(dialog_title='Select a directory'):
    """
    Necessary import statement:
    import os, sys, tkinter
    from tkinter import filedialog
    """
    #[1] Initiate and hide the main window.
    root = tkinter.Tk()
    root.withdraw()
    
    try:
        path_dir = tkinter.filedialog.askdirectory(title=dialog_title)
        if path_dir:
            #[2] Extract the base name of the selected directory.
            bsn_dir = os.path.basename(path_dir)
            #[3] Clean the path and append the trailing separator.
            path_dir = os.path.normpath(path_dir) + os.sep
            print('--path_dir:', path_dir)
            return path_dir, bsn_dir
        else:
            #[4] Exit the program if no directory is selected.
            print('--No directory selected. Exiting.')
            sys.exit()
    except Exception as e:
        print(f'--An error occurred: {e}')
        return None, None
    finally:
        #[5] Clean up and destroy the Tkinter window.
        root.destroy()
        
#[7] tkinter select file or folder - End





# [8] Start
def check_attributes_of_an_object(obj):
    # Get all attributes and methods of the object
    attributes = dir(obj)
    for attr in attributes:
        try:
            # Attempt to get the value of the attribute
            value = getattr(obj, attr)
            # Check if the attribute is callable (i.e., a method)
            # and skip it to avoid calling functions unintentionally
            if callable(value):
                print(f'{attr}: <method or callable>')
            else:
                print(f'{attr}: {value}')
        except Exception as e:
            # If the attribute couldn't be accessed, print a message
            print(f'{attr}: <could not access, reason: {e}>')
            






def print_variable_sizes(scope_vars, text_note=None):
    """
    Prints the size of all variables in the given scope in a tabular format.
    Args: scope_vars (dict): A dictionary of variables (e.g., locals() or globals()).
    Usage: M1F.print_variable_sizes(locals())
    gc.collect()
    """
    #[1] Create a list to store variable details
    var_data = []
    total_size_bytes = 0

    for var_name, var_value in scope_vars.items():
        try:
            size_in_bytes = sys.getsizeof(var_value)
            size_in_kb = size_in_bytes / 1024
            total_size_bytes += size_in_bytes
            var_data.append({"Variable Name": var_name, 
                             "Size (Bytes)": size_in_bytes, 
                             "Size (KB)": f"{size_in_kb:.2f}"})
        except Exception as e:
            var_data.append({"Variable Name": var_name, 
                             "Size (Bytes)": "Error", 
                             "Size (KB)": str(e)})

    #[2] Add percentage column
    for var in var_data:
        if isinstance(var["Size (Bytes)"], int):  # Ensure it's a valid size
            var["Pct (%)"] = f"{(var['Size (Bytes)'] / total_size_bytes) * 100:.2f}"
        else:
            var["Pct (%)"] = "Error"

    #[3] Convert to a Pandas DataFrame
    df_var_size = pd.DataFrame(var_data)

    #[4] Print the DataFrame as a table
    timestamp = datetime.now().strftime("%Y-%m%d-%H%M%S")
    print(f'\n[print_variable_sizes] {timestamp} {text_note}:')
    print(f'{tabulate(df_var_size, headers="keys", tablefmt="orgtbl")}\nTotal Size (KB): {total_size_bytes / 1024:.2f}\n\n')
    return df_var_size








# [8] End
























